import { PublicKey } from '@solana/web3.js';
import {
  CLOAK_DEFAULT_RELAY_URL,
  CLOAK_FIXED_FEE_LAMPORTS,
  CLOAK_MAINNET_PROGRAM_ID,
  CLOAK_MIN_SOL_DEPOSIT_LAMPORTS,
  CLOAK_NATIVE_SOL_MINT,
  CLOAK_VARIABLE_FEE_DENOMINATOR,
  CLOAK_VARIABLE_FEE_NUMERATOR,
} from '@gorkh/shared';

export const GORKH_CLOAK_PROGRAM_ID = CLOAK_MAINNET_PROGRAM_ID;
export const GORKH_CLOAK_RELAY_URL = CLOAK_DEFAULT_RELAY_URL;
export const GORKH_CLOAK_NATIVE_SOL_MINT = CLOAK_NATIVE_SOL_MINT;
export const GORKH_CLOAK_MIN_SOL_DEPOSIT_LAMPORTS = CLOAK_MIN_SOL_DEPOSIT_LAMPORTS;
export const GORKH_CLOAK_FIXED_FEE_LAMPORTS = CLOAK_FIXED_FEE_LAMPORTS;
export const GORKH_CLOAK_VARIABLE_FEE_NUMERATOR = CLOAK_VARIABLE_FEE_NUMERATOR;
export const GORKH_CLOAK_VARIABLE_FEE_DENOMINATOR = CLOAK_VARIABLE_FEE_DENOMINATOR;
export const GORKH_CLOAK_CIRCUITS_BASE_URL =
  'https://cloak-circuits.s3.us-east-1.amazonaws.com/circuits/0.1.0';
export const GORKH_CLOAK_MERKLE_TREE_HEIGHT = 32;
export const GORKH_CLOAK_PROOF_BYTES = 256;
export const GORKH_CLOAK_PUBLIC_INPUT_BYTES = 264;

export const GORKH_CLOAK_SUPPORTED_ASSETS = ['SOL', 'USDC', 'USDT'] as const;
export type CloakSupportedAsset = (typeof GORKH_CLOAK_SUPPORTED_ASSETS)[number];

export function getCloakProgramPublicKey(): PublicKey {
  return new PublicKey(GORKH_CLOAK_PROGRAM_ID);
}
